// 0 对应 A，1 对应 B，2 对应 C, 3 对应 D
var arrche = [
            {
                "qus":"猜猜是哪部车？",
                "a":"DS7 SUV",
                "b":"保时捷 Sport Turismo",
                "c":"海马SGOO",
                "d":"迈凯伦Senna",
                "anser":"0",
                "img":"css/images/pic3.jpg",
                "bigimg":"css/images/pic3big.jpg",
                "daan":"DS7 SUV"
                
            },
            {
                "qus":"猜猜是哪部车？",
                "a":"北京现代 ENCINO",
                "b":"Ford F50 猛禽",
                "c":"劳斯莱斯古斯特高级定制版",
                "d":"奇点is6",
                "anser":"1",
                "img":"css/images/pic4.jpg",
                "bigimg":"css/images/pic4big.jpg",
                "daan":"Ford F50 猛禽"
            },
            {
                "qus":"猜猜是哪部车？",
                "a":"别克新一代君越",
                "b":"观致MILE 1",
                "c":"JEEP 新一代牧马人",
                "d":"前途K20 Concept",
                "anser":"2",
                "img":"css/images/pic5.jpg",
                "bigimg":"css/images/pic5big.jpg",
                "daan":"JEEP 新一代牧马人"
            },
            {
              "qus":"猜猜是哪部车？",
                "a":"宾利 Contionental GT",
                "b":"广汽三菱Eclipse Cross",
                "c":"乔治巴顿 GX",
                "d":"MINI COOPER",
                "anser":"3",
               "img":"css/images/pic6.jpg",
                "bigimg":"css/images/pic6big.jpg",
                "daan":"MINI COOPER"
            },
            {
              "qus":"猜猜是哪部车？",
                "a":"WEY-X",
                "b":"博瑞GE",
                "c":"广汽Acura CDX SPORT HYBRID",
                "d":"特斯拉 ModelS",
                "anser":"0",
               "img":"css/images/pic7.jpg",
                "bigimg":"css/images/pic7big.jpg",
                "daan":"WEY-X"
            },
            {
              "qus":"猜猜是哪部车？",
                "a":"东风A60 RACE CAR",
                "b":"雷克萨斯ES",
                "c":"阿斯顿马丁 DB11",
                "d":"沃尔沃 北极星polestar",
                "anser":"2",
                "img":"css/images/pic9.jpg",
                "bigimg":"css/images/pic9big.jpg",
                "daan":"阿斯顿马丁 DB11"
            },
            {
              "qus":"猜猜是哪部车？",
                "a":"东风日产 聆风LEAF",
                "b":"林肯 飞行家Aviator",
                "c":"正道HK GT",
                "d":"奥迪R8 V10plus",
                "anser":"3",
                "img":"css/images/pic10.jpg",
                "bigimg":"css/images/pic10big.jpg",
                "daan":"奥迪R8 V10plus"
            },
            {
               "qus":"猜猜是哪部车？",
                "a":"拜腾 BYTON Concept",
                "b":"丰田C-HR",
                "c":"玛莎拉蒂 总裁2018款",
                "d":"DS7 SUV",
                "anser":"0",
               "img":"css/images/pic11.jpg",
                "bigimg":"css/images/pic11big.jpg",
                "daan":"拜腾 BYTON Concept"
            },
            {
                "qus":"猜猜是哪部车？",
                "a":"劳斯莱斯古斯特高级定制版",
                "b":"奇点is6",
                "c":"北京现代 ENCINO",
                "d":"JEEP 新一代牧马人",
                "anser":"2",
               "img":"css/images/pic13.jpg",
                "bigimg":"css/images/pic13big.jpg",
                "daan":"北京现代 ENCINO"
            },
            {
                "qus":"猜猜是哪部车？",
                "a":"观致MILE 1",
                "b":"前途K20 Concept",
                "c":"MINI COOPER",
                "d":"别克新一代君越",
                "anser":"3",
                "img":"css/images/pic14.jpg",
                "bigimg":"css/images/pic14big.jpg",
                "daan":"别克新一代君越"
            },
            {
                "qus":"猜猜是哪部车？",
                "a":"宾利 Contionental GT",
                "b":"广汽三菱Eclipse Cross",
                "c":"乔治巴顿 GX",
                "d":"WEY-X",
                "anser":"0",
                "img":"css/images/pic15.jpg",
                "bigimg":"css/images/pic15big.jpg",
                "daan":"宾利 Contionental GT"
            },
            {
               "qus":"猜猜是哪部车？",
                "a":"广汽Acura CDX SPORT HYBRID",
                "b":"博瑞GE",
                "c":"特斯拉 ModelS",
                "d":"阿尔法罗密欧四叶草版",
                "anser":"1",
               "img":"css/images/pic16.jpg",
                "bigimg":"css/images/pic16big.jpg",
                "daan":"博瑞GE"
            },
            {
                "qus":"猜猜是哪部车？",
                "a":"红旗概念车",
                "b":"蔚来ES",
                "c":"东风标致 cs10 2018款",
                "d":"阿斯顿马丁 DB11",
                "anser":"2",
               "img":"css/images/pic17.jpg",
                "bigimg":"css/images/pic17big.jpg",
                "daan":"东风标致 cs10 2018款"
            },
            {
                "qus":"猜猜是哪部车？",
                "a":"雷克萨斯ES",
                "b":"沃尔沃 北极星polestar",
                "c":"奥迪R8 V10plus",
                "d":"东风A60 RACE CAR",
                "anser":"3",
                "img":"css/images/pic18.jpg",
                "bigimg":"css/images/pic18big.jpg",
                "daan":"东风A60 RACE CAR"
            },
            {
                "qus":"猜猜是哪部车？",
                "a":"东风日产 聆风LEAF",
                "b":"林肯 飞行家Aviator",
                "c":"正道HK GT",
                "d":"拜腾 BYTON Concept",
                "anser":"0",
               "img":"css/images/pic19.jpg",
                "bigimg":"css/images/pic19big.jpg",
                "daan":"东风日产 聆风LEAF"
            },
            {
                "qus":"猜猜是哪部车？",
                "a":"玛莎拉蒂 总裁2018款",
                "b":"丰田C-HR",
                "c":"DS7 SUV",
                "d":"保时捷 Sport Turismo",
                "anser":"1",
                "img":"css/images/pic20.jpg",
                "bigimg":"css/images/pic20big.jpg",
                "daan":"丰田C-HR"
            },
            {
                "qus":"猜猜是哪部车？",
                "a":"迈凯伦Senna",
                "b":"Ford F50 猛禽",
                "c":"海马SGOO",
                "d":"北京现代 ENCINO",
                "anser":"2",
               "img":"css/images/pic21.jpg",
                "bigimg":"css/images/pic21big.jpg",
                "daan":"海马SGOO"
            },
            {
               "qus":"猜猜是哪部车？",
                "a":"奇点is6",
                "b":"JEEP 新一代牧马人",
                "c":"别克新一代君越",
                "d":"劳斯莱斯古斯特高级定制版",
                "anser":"3",
                "img":"css/images/pic22.jpg",
                "bigimg":"css/images/pic22big.jpg",
                "daan":"劳斯莱斯古斯特高级定制版"
            },
            {
               "qus":"猜猜是哪部车？",
                "a":"观致MILE 1",
                "b":"前途K20 Concept",
                "c":"MINI COOPER",
                "d":"宾利 Contionental GT",
                "anser":"0",
                "img":"css/images/pic23.jpg",
                "bigimg":"css/images/pic23big.jpg",
                "daan":"观致MILE 1"
            },
            {
               "qus":"猜猜是哪部车？",
                "a":"乔治巴顿 GX",
                "b":"广汽三菱Eclipse Cross",
                "c":"WEY-X",
                "d":"博瑞GE",
                "anser":"1",
               "img":"css/images/pic24.jpg",
                "bigimg":"css/images/pic24big.jpg",
                "daan":"广汽三菱Eclipse Cross"
            },
            {
               "qus":"猜猜是哪部车？",
                "a":"特斯拉 ModelS",
                "b":"阿尔法罗密欧四叶草版",
                "c":"广汽Acura CDX SPORT HYBRID",
                "d":"东风标致 cs10 2018款",
                "anser":"2",
                "img":"css/images/pic25.jpg",
                "bigimg":"css/images/pic25big.jpg",
                "daan":"广汽Acura CDX SPORT HYBRID"
            },
            {
               "qus":"猜猜是哪部车？",
                "a":"蔚来ES",
                "b":"阿斯顿马丁 DB11",
                "c":"东风A60 RACE CAR",
                "d":"红旗概念车",
                "anser":"3",
                "img":"css/images/pic26.jpg",
                "bigimg":"css/images/pic26big.jpg",
                "daan":"红旗概念车"
            },
            {
               "qus":"猜猜是哪部车？",
                "a":"雷克萨斯ES",
                "b":"沃尔沃 北极星polestar",
                "c":"奥迪R8 V10plus",
                "d":"东风日产 聆风LEAF",
                "anser":"0",
                "img":"css/images/pic27.jpg",
                "bigimg":"css/images/pic27big.jpg",
                "daan":"雷克萨斯ES"
            },
            {
               "qus":"猜猜是哪部车？",
                "a":"正道HK GT",
                "b":"林肯 飞行家Aviator",
                "c":"拜腾 BYTON Concept",
                "d":"丰田C-HR",
                "anser":"1",
                "img":"css/images/pic28.jpg",
                "bigimg":"css/images/pic28big.jpg",
                "daan":"林肯 飞行家Aviator"
            },
            {
               "qus":"猜猜是哪部车？",
                "a":"DS7 SUV",
                "b":"保时捷 Sport Turismo",
                "c":"玛莎拉蒂 总裁2018款",
                "d":"海马SGOO",
                "anser":"2",
                "img":"css/images/pic29.jpg",
                "bigimg":"css/images/pic29big.jpg",
                "daan":"玛莎拉蒂 总裁2018款"
            },
            {
               "qus":"猜猜是哪部车？",
                "a":"Ford F50 猛禽",
                "b":"北京现代 ENCINO",
                "c":"劳斯莱斯古斯特高级定制版",
                "d":"迈凯伦Senna",
                "anser":"3",
                "img":"css/images/pic30.jpg",
                "bigimg":"css/images/pic30big.jpg",
                "daan":"迈凯伦Senna"
            },
            {
               "qus":"猜猜是哪部车？",
                "a":"奇点is6",
                "b":"JEEP 新一代牧马人",
                "c":"别克新一代君越",
                "d":"观致MILE 1",
                "anser":"0",
                "img":"css/images/pic31.jpg",
                "bigimg":"css/images/pic31big.jpg",
                "daan":"奇点is6"
            },
            {
               "qus":"猜猜是哪部车？",
                "a":"MINI COOPER",
                "b":"前途K20 Concept",
                "c":"宾利 Contionental GT",
                "d":"广汽三菱Eclipse Cross",
                "anser":"1",
                "img":"css/images/pic32.jpg",
                "bigimg":"css/images/pic32big.jpg",
                "daan":"前途K20 Concept"
            },
            {
              "qus":"猜猜是哪部车？",
                "a":"WEY-X",
                "b":"博瑞GE",
                "c":"乔治巴顿 GX",
                "d":"广汽Acura CDX SPORT HYBRID",
                "anser":"2",
                "img":"css/images/pic33.jpg",
                "bigimg":"css/images/pic33big.jpg",
                "daan":"乔治巴顿 GX"
            },
            {
              "qus":"猜猜是哪部车？",
                "a":"阿尔法罗密欧四叶草版",
                "b":"东风标致 cs10 2018款",
                "c":"红旗概念车",
                "d":"特斯拉 ModelS",
                "anser":"3",
                "img":"css/images/pic34.jpg",
                "bigimg":"css/images/pic34big.jpg",
                "daan":"特斯拉 ModelS"
            },
            {
               "qus":"猜猜是哪部车？",
                "a":"蔚来ES",
                "b":"阿斯顿马丁 DB11",
                "c":"东风A60 RACE CAR",
                "d":"雷克萨斯ES",
                "anser":"0",
                "img":"css/images/pic35.jpg",
                "bigimg":"css/images/pic35big.jpg",
                "daan":"蔚来ES"
            },
            {
              "qus":"猜猜是哪部车？",
                "a":"奥迪R8 V10plus",
                "b":"沃尔沃 北极星polestar",
                "c":"东风日产 聆风LEAF",
                "d":"林肯 飞行家Aviator",
                "anser":"1",
                "img":"css/images/pic36.jpg",
                "bigimg":"css/images/pic36big.jpg",
                "daan":"沃尔沃 北极星polestar"
            },
            {
              "qus":"猜猜是哪部车？",
                "a":"拜腾 BYTON Concept",
                "b":"丰田C-HR",
                "c":"正道HK GT",
                "d":"玛莎拉蒂 总裁2018款",
                "anser":"2",
                "img":"css/images/pic37.jpg",
                "bigimg":"css/images/pic37big.jpg",
                "daan":"正道HK GT"
            }
];
